# Generated by Django 5.2 on 2025-09-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0001_initial'),
        ('sheet_models', '0005_cleaneddata_encoder_cleaneddata_normalier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerWheights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights_file', models.FileField(upload_to='model_weights/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_weights', to='sheet_models.ml_models')),
            ],
        ),
    ]
