# Generated by Django 5.2 on 2025-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_models',
            name='model_type',
            field=models.CharField(blank=True, choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering')], max_length=20, null=True),
        ),
    ]
