# Generated by Django 5.2 on 2025-09-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_models', '0002_alter_ml_models_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_data', models.FileField(upload_to='cleaned_data_files/')),
                ('target_column', models.CharField(help_text='Name of the target column', max_length=100)),
                ('size', models.PositiveIntegerField(help_text='Size of the cleaned data in bytes')),
                ('type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON'), ('xml', 'XML')], default='csv', help_text='Type/format of the cleaned data file', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_cleaned_data', to='sheet_models.analysis')),
            ],
        ),
    ]
