# Generated by Django 5.2 on 2025-09-03 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_models', '0003_cleaneddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelhyperparameters',
            name='parameter_name',
        ),
        migrations.RemoveField(
            model_name='modelhyperparameters',
            name='value',
        ),
        migrations.AddField(
            model_name='modelhyperparameters',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='modelhyperparameters',
            name='hyperparams',
            field=models.JSONField(blank=True, help_text='Hyperparameters as a JSON object', null=True),
        ),
    ]
