# Generated by Django 5.2 on 2025-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_models', '0004_remove_modelhyperparameters_parameter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneddata',
            name='encoder',
            field=models.CharField(blank=True, help_text='Encoder used for categorical variables', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleaneddata',
            name='normalier',
            field=models.CharField(blank=True, help_text='Normalizer used for feature normalization', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cleaneddata',
            name='scaller',
            field=models.CharField(blank=True, help_text='Scaler used for feature scaling', max_length=100, null=True),
        ),
    ]
