# Generated by Django 5.2 on 2025-08-07 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(default='default.jpg', upload_to='user_images/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('deep-sea', 'Deep Sea'), ('dark', 'Dark'), ('burry', 'Burry'), ('military', 'Military'), ('ice', 'Ice')], default='light', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
