# Generated by Django 5.2 on 2025-08-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_model_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='user_image',
            field=models.ImageField(default='defult-user-profile-image.png', upload_to='user_images/'),
        ),
    ]
