# Generated by Django 5.2 on 2025-08-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheet_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ImageField(upload_to='charts/')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet_models.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet_models.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet_models.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet_models.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.JSONField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet_models.analysis')),
            ],
        ),
    ]
