# Generated by Django 5.2 on 2025-08-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('sheet_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='sheet_models.analysis'),
        ),
        migrations.AlterField(
            model_name='columndescription',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_desciptions', to='sheet_models.analysis'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='sheet_models.analysis'),
        ),
        migrations.AlterField(
            model_name='descriptivestatistics',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptive_statistics', to='sheet_models.analysis'),
        ),
        migrations.AlterField(
            model_name='qualityreport',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='sheet_models.analysis'),
        ),
    ]
