# Generated by Django 5.2 on 2025-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_chart_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='chart',
        ),
        migrations.AddField(
            model_name='chart',
            name='plot_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
